name: CI Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        target: [debug, release]
        #platform: [windows, x11, android, uwp, javascript, web, osx, iphone]
        platform: [windows, x11, android, osx]
        include:
          - platform: windows
            OS: windows-latest
          - platform: x11
            OS: linux-latest
            TARGET: x86_64-unknown-linux-musl
            COMPILER: gcc
            LINKER: gcc
          - platform: android
            OS: linux-latest
          - platform: osx
            OS: macos-latest
            TARGET: x86_64-apple-darwin
            COMPILER: clang
            LINKER: clang
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodule: recursive
      - name: Install Linux dependencies
        if: matrix.platform == 'x11'
        run: sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev
      - name: Install dependencies
        run: python -m pip install scons
      - name: Echo Versions
        run: python --version && scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: ${{ matrix.platform }}-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform = ${{ matrix.platform }} generate_bindings=yes -j2 target=${{ matrix.target }}
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform = ${{ matrix.platform }} -j2 target=${{ matrix.target }}
        