name: CI Build
on: [push, pull_request]

#platform: [windows, x11, android, uwp, javascript, web, osx, iphone]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: python -m pip install scons
      - name: Echo Versions
        run: |
          python --version
          scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: windows-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=windows generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=windows -j2
  build_x11:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
          python3 -m pip install scons
      - name: Echo Versions
        run: |
          python3 --version
          scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: x11-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=x11 generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=x11 -j2
  build_osx:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          brew install scons yasm
          python -m pip install scons
      - name: Echo Versions
        run: |
          python --version
          scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: osx-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=x11 generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=x11 -j2