name: CI Build
on: [push, pull_request]

#platform: [windows, x11, android, uwp, javascript, web, osx, iphone]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: python -m pip install scons
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Echo Versions
        run: |
          python --version
          scons --version
          msbuild -version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: windows-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=windows generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=windows -j2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-dll
          path: addons/gdfastnoise/bin/win64/libfastnoise.dll
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      - name: Echo Versions
        run: |
          python3 --version
          scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: linux-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=linux generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=linux -j2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-dll
          path: addons/gdfastnoise/bin/x11/libfastnoise.so
  build_osx:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install scons yasm
      - name: Echo Versions
        run: |
          python --version
          scons --version
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v2
        with:
          path: godot-cpp
          key: osx-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=osx generate_bindings=yes -j2
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=osx -j2
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-dll
          path: addons/gdfastnoise/bin/osx/libfastnoise.dylib